# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c9b5ef244e342a1cbf3f71bbe5180e8e3a11b010c2f6e59bab1d1b98b5d45486e17fa40e04928aa06396ebaa089656d8b30f75218af72d1a8d818f442f5d3bff

test:
  secret_key_base: 6d838d8381a6d38fa2a44594bd127dc2cb6fdc7d96b26530a872e22208bc874553de279c5179751139e374aa34375c5fc060c598d1037e66eacc2fab4b5b2f91

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
